# Generated by Django 3.1 on 2022-08-29 04:45

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shop.models.user_directory_path),
        ),
    ]
