# Generated by Django 3.1 on 2022-09-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220902_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
