# Generated by Django 3.1 on 2022-09-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
    ]
