# Generated by Django 3.1 on 2022-09-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_category_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='newsletter_email',
        ),
    ]
