# Generated by Django 3.1 on 2022-09-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220905_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='newsletter_email',
            new_name='email',
        ),
    ]
