# Generated by Django 3.1 on 2022-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220906_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'black'), ('WHITE', 'white'), ('RED', 'red'), ('BLUE', 'red'), ('GREEN', 'green')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=30, null=True),
        ),
    ]
