# Generated by Django 3.2.15 on 2022-09-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
