# Generated by Django 3.2.15 on 2022-09-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20220926_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='star',
        ),
    ]
