# Generated by Django 3.2.15 on 2022-09-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
