# Generated by Django 3.2.15 on 2022-09-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billing',
            name='address2',
            field=models.CharField(max_length=100),
        ),
    ]
