# Generated by Django 3.2.15 on 2022-09-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20220928_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billing',
            new_name='Shipping',
        ),
    ]
