# Generated by Django 3.2.15 on 2022-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_rename_billing_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
