# Generated by Django 3.2.15 on 2022-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(error_messages={'error': 'not more than 5 star'}, max_length=5),
        ),
    ]
