# Generated by Django 3.2.15 on 2022-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.PositiveIntegerField(blank=True, error_messages={'error': 'not more than 5 star'}, max_length=5, null=True),
        ),
    ]
