# Generated by Django 3.2.15 on 2022-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'error': 'not more than 5 star'}, help_text='not more than 5 stars', max_length=5, null=True),
        ),
    ]
