# Generated by Django 3.2.15 on 2022-09-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
