# Generated by Django 3.2.15 on 2022-10-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20221004_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
    ]
