# Generated by Django 3.2.15 on 2022-11-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20221031_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
