# Generated by Django 3.2.15 on 2022-11-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alter_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
