# Generated by Django 3.2.15 on 2022-11-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
