# Generated by Django 3.2.15 on 2022-11-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='net_price',
        ),
    ]
